---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
        ignore: 'order-alphabetical'
files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'